name: CI

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        laravel: [6.*, 7.*, 8.*, 9.*]
        php: [ 7.2, 7.3, 7.4, 8.0, 8.1 ]
        dependency-version: [prefer-stable]
        exclude:
          - php: 7.2
            laravel: 9.*
          - php: 7.3
            laravel: 9.*
          - php: 7.4
            laravel: 9.*
          - php: 7.2
            laravel: 8.*
          - php: 8.1
            laravel: 7.*
        include:
          - php: 8.0
            laravel: 9.x
            testbench: 7.*
            dependency-version: prefer-stable
          - laravel: 8.*
            testbench: 6.*
          - laravel: 7.*
            testbench: 5.*
          - laravel: 6.*
            testbench: 4.*

    name: PHP ${{ matrix.php }}  - Laravel ${{ matrix.laravel }} - Testbench ${{ matrix.testbench }} (${{ matrix.dependency-version }})

    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Cache dependencies
      uses: actions/cache@v1
      with:
        path: ~/.composer/cache/files
        key: dependencies-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: mbstring, zip
        coverage: pcov

    - name: Install dependencies
      run: |
        composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
        composer update --${{ matrix.dependency-version }} --no-interaction --prefer-dist --no-suggest

    - name: Execute & Run tests
      run: vendor/bin/phpunit
